parserOptions: 
    ecmaVersion: 6
    sourceType: module

env:
    browser: true
    node: true

extends:
    - "eslint:recommended"

rules:
    quotes:
        - error
        - double
        - avoidEscape: true
          allowTemplateLiterals: true

    semi: ["error", "always"]
    no-unreachable: error
    spaced-comment: ["error", "always"]
    no-unused-vars: error
    no-console: off
